# Generated by Django 4.2.4 on 2023-12-10 05:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_post_likes_alter_post_id_alter_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='liked_post',
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_post', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followers', models.ManyToManyField(blank=True, related_name='followers_set', to='network.profile')),
                ('following', models.ManyToManyField(blank=True, related_name='following_set', to='network.profile')),
            ],
        ),
    ]
