# Generated by Django 4.2.4 on 2023-12-23 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_tweets'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='tweets',
        ),
    ]
