# Generated by Django 4.2.4 on 2024-01-05 04:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_user_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='posts',
        ),
    ]
